import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentProfile } from "@/lib/auth/current-user";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { MemberActions } from "@/components/admin/member-actions";
import { WithdrawalActions } from "@/components/admin/withdrawal-actions";
import { SeasonManager } from "@/components/admin/season-manager";
import { OperationsSettings } from "@/components/admin/operations-settings";

export default async function AdminPage(){const profile=await getCurrentProfile();if(profile?.role!=="admin")redirect("/dashboard");const admin=createSupabaseAdminClient();const[{data:members},{data:withdrawals},{data:settings},{data:seasons}]=await Promise.all([admin.from("profiles").select("user_id,login_id,name,email,role,staff_position,account_status,approval_status,ranking_excluded,created_at").order("created_at",{ascending:false}),admin.from("withdrawal_requests").select("*,profiles:user_id(name,login_id)").in("status",["pending","approved"]).is("auth_deleted_at",null),admin.from("system_settings").select("*"),admin.from("seasons").select("*").order("starts_on",{ascending:false})]);const maintenance=(settings?.find(x=>x.setting_key==="maintenance")?.setting_value??{}) as Record<string,unknown>;const scorePolicy=(settings?.find(x=>x.setting_key==="score_policy")?.setting_value??{}) as Record<string,unknown>;return <main className="mx-auto min-h-screen max-w-6xl px-6 py-12"><header className="flex justify-between"><div><p className="font-bold text-emerald-600">ADMIN</p><h1 className="text-3xl font-black">관리자 대시보드</h1></div><Link href="/dashboard">대시보드</Link></header><section className="mt-8 grid gap-3 sm:grid-cols-4"><Card label="전체 회원" value={members?.length??0}/><Card label="승인 대기" value={members?.filter(x=>x.approval_status==="pending").length??0}/><Card label="운영진" value={members?.filter(x=>x.role==="staff").length??0}/><Card label="탈퇴 대기" value={withdrawals?.length??0}/></section>{Boolean(withdrawals?.length)&&<section className="mt-10"><h2 className="text-xl font-black">탈퇴 승인</h2><div className="mt-4 space-y-2">{withdrawals?.map(w=><div key={w.request_id} className="flex justify-between rounded-xl border border-red-100 p-4"><div><b>{Array.isArray(w.profiles)?w.profiles[0]?.name:w.profiles?.name}</b><p className="text-sm text-zinc-500">{w.reason||"사유 없음"}</p></div><WithdrawalActions requestId={w.request_id} retry={w.status==="approved"}/></div>)}</div></section>}<section className="mt-10"><h2 className="text-xl font-black">회원 관리</h2><div className="mt-4 space-y-3">{members?.map(m=><article key={m.user_id} className="grid gap-4 rounded-2xl border p-4 lg:grid-cols-[1fr_2fr]"><div><b>{m.name}</b><p className="text-sm text-zinc-500">{m.login_id} · {m.email}</p></div><MemberActions userId={m.user_id} role={m.role} position={m.staff_position} status={m.account_status} excluded={m.ranking_excluded}/></article>)}</div></section><section className="mt-10"><h2 className="text-xl font-black">시즌 관리</h2><SeasonManager seasons={seasons??[]}/></section><section className="mt-10"><h2 className="text-xl font-black">운영 설정</h2><OperationsSettings maintenance={maintenance} scorePolicy={scorePolicy}/></section></main>}
function Card({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-zinc-50 p-5"><p className="text-sm text-zinc-500">{label}</p><b className="text-3xl">{value}</b></div>}
